- name: GCP 인프라 프로비저닝
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    gcp_project: "{{ lookup('env', 'GCP_PROJECT_ID') }}" # GitHub Secrets에서 주입
    gcp_service_account_email: "{{ lookup('env', 'GCP_SA_EMAIL') }}" # GitHub Secrets에서 주입
    zone: "europe-west10-a" # 서유럽
    ssh_user: "ansible_user"
    ssh_pub_key: "{{ lookup('file', 'gcp_key.pub') }}" # 리포지토리의 공개 키 파일

  tasks:
    - name: GCE 인스턴스 생성
      google.cloud.gcp_compute_instance:
        name: "web-server-01"
        machine_type: "f1-micro"
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        # (핵심) WIF를 통해 얻은 'Application Default Credentials'를 자동으로 사용
        auth_kind: "application" 

        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "projects/debian-cloud/global/images/family/debian-11"
        network_interfaces:
          - access_configs: # 외부 IP 할당
              - name: "External NAT"
                type: "ONE_TO_ONE_NAT"

        # (핵심) 1단계의 공개 키를 'ansible_user' 사용자의 SSH 키로 등록
        metadata:
          ssh-keys: "{{ ssh_user }}:{{ ssh_pub_key }}"

        tags:
          items:
            - http-server # 방화벽 등에 사용할 태그

        state: present
